# Forked from eKatchko/public-bioinformatics-databases

name: Process changed files

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'
    paths:
      - 'databases/**.json'
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "changed-files"
  changed-files:
    # The type of runner that the job will run on
    runs-on: [self-hosted, fts3]
    environment: APPROVAL_REQUIRED

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v16
        with:
          since_last_remote_commit: "true"
          files: |
            databases/*.json
            
      - name: Get changed files with git diff
        id: git-diff
        run: |
          git diff --name-only -r main origin/fix/client_ip | grep databases/** >> $GITHUB_OUTPUT
      
      - name: Check output
        run: echo "${{ steps.git-diff.outputs }}"
            
      - name: Send changed files to fts3-connector
        if: steps.changed-files.outputs.only_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Calling with $file"
            curl -H "X-AUTH-HEADER: ${{ secrets.FTS3_CLIENT_API_KEY }}" -H "Content-Type: application/json" -X POST -d @$file "${{ env.FTS3_CLIENT_ENDPOINT }}/transfer/dry"
          done
