name: Transfer All Files

on:
  workflow_dispatch:
  
  schedule:
    - cron:  '30 5,17 * * *'

  
jobs:
     
  transfer-all-files:
    strategy:
      fail-fast: false
      matrix:
        FILENAME:
          - databases/blast.json
          - databases/gtdb-tk.json
          - databases/card.json
          - databases/checkm.json
          - databases/plsdb.json
          - databases/alphafold.json


          # Add more files as needed
    uses: ./.github/workflows/transfer_file.yml
    with:
          FILENAME: ${{ matrix.FILENAME }}
    secrets: inherit
