name: Transfer All Files

on:
  workflow_dispatch:
  
  schedule:
    - cron:  '30 5,17 * * *'

  
jobs:
  list-databases:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - uses: actions/checkout@v4
        - id: set-matrix
          run: echo "::set-output name=matrix::$(ls databases/*.json | jq -R -s -c 'split("\n")[:-1]')"
     
  transfer-all-files:
    needs: list-databases
    strategy:
      fail-fast: false
      matrix:
        FILENAME: ${{ fromJson(needs.list-databases.outputs.matrix) }}

          # Add more files as needed
    uses: ./.github/workflows/transfer_file.yml
    with:
          FILENAME: ${{ matrix.FILENAME }}
    secrets: inherit
