name: Validate JSONs

on:
  workflow_call:
   inputs:
     FILENAME:
      required: true
      type: string
  
  workflow_dispatch:
    inputs:
      FILENAME:
        required: true
        type: string

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./databases/database_schema.json
          INPUT_JSONS: ./databases/${{ inputs.FILENAME || github.event.inputs.FILENAME }}"
